version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  elasticsearch:
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    image: elasticsearch
  web:
    build: .
    env_file: .env
    command: bash -c "sleep 5; python manage.py migrate && python manage.py loaddata tests && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings_docker
    depends_on:
      - elasticsearch
      - db
