version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  elasticsearch:
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    image: elasticsearch
  web:
    build: .
    env_file: .env
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - /code/node_modules
      - /code/app/l8pr/static/bower_components
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings_docker
    depends_on:
      - elasticsearch
      - db
