version: '2'
services:
  db:
    image: postgres
  elasticsearch:
    image: elasticsearch
  web:
    build: .
    # env_file: .env
    command: bash -c "sleep 5; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings_docker
    depends_on:
      - elasticsearch
      - db
