# MONGO_HOST = 'localhost'
# MONGO_PORT = 27017
# MONGO_USERNAME = 'user'
# MONGO_PASSWORD = 'user'
# MONGO_DBNAME = 'apitest'
DOMAIN = {'people': {}}
URL_PREFIX = 'api'
DEBUG = True
LESS_BIN = 'node_modules/.bin/lessc'
