# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-18 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('provider_name', models.CharField(choices=[('YouTube', 'YouTube'), ('SoundCloud', 'SoundCloud')], max_length=255)),
                ('html', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('show_type', models.CharField(choices=[('MusicShow', 'MusicShow'), ('VideoShow', 'VideoShow')], max_length=10)),
                ('loop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='l8pr.Loop')),
            ],
        ),
        migrations.CreateModel(
            name='ShowSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuffle', models.BooleanField(default=False)),
                ('dj_layout', models.BooleanField(default=False)),
                ('giphy', models.BooleanField(default=True)),
                ('giphy_tags', models.TextField(blank=True, null=True)),
                ('hide_strip', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShowsRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l8pr.Loop')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l8pr.Show')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='show', to='l8pr.ShowSettings'),
        ),
        migrations.AddField(
            model_name='show',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loop',
            name='shows_list',
            field=models.ManyToManyField(related_name='ShowsRelationship', through='l8pr.ShowsRelationship', to='l8pr.Show'),
        ),
        migrations.AddField(
            model_name='loop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='l8pr.Show'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='item',
            order_with_respect_to='show',
        ),
    ]
