# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
