# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-20 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0002_auto_20160518_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name='item',
            order_with_respect_to=None,
        ),
        migrations.AddField(
            model_name='itemsrelationship',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l8pr.Item'),
        ),
        migrations.AddField(
            model_name='itemsrelationship',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l8pr.Show'),
        ),
        migrations.AddField(
            model_name='show',
            name='items_list',
            field=models.ManyToManyField(related_name='ItemsRelationship', through='l8pr.ItemsRelationship', to='l8pr.Item'),
        ),
    ]
