# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0003_auto_20160306_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuffle', models.BooleanField(default=False)),
                ('djLayout', models.BooleanField(default=False)),
                ('giphy', models.TextField(blank=True, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='l8pr.Show')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='provider_name',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('SoundCloud', 'SoundCloud')], default='YouTube', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='l8pr.Show'),
        ),
    ]
