# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-20 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0003_auto_20160520_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='show',
        ),
    ]
