# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-20 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0004_remove_item_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='items_list',
            new_name='items',
        ),
    ]
