# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0004_auto_20160309_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsettings',
            name='giphyTags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showsettings',
            name='giphy',
            field=models.BooleanField(default=True),
        ),
    ]
