# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-20 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0005_auto_20160520_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='loop',
        ),
    ]
