# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0005_auto_20160309_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showsettings',
            old_name='djLayout',
            new_name='dj_layout',
        ),
        migrations.RenameField(
            model_name='showsettings',
            old_name='giphyTags',
            new_name='giphy_tags',
        ),
        migrations.AddField(
            model_name='showsettings',
            name='hide_strip',
            field=models.BooleanField(default=False),
        ),
    ]
