# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0006_auto_20160309_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='id',
        ),
        migrations.RemoveField(
            model_name='showsettings',
            name='show',
        ),
        migrations.AddField(
            model_name='show',
            name='settings',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='l8pr.ShowSettings'),
            preserve_default=False,
        ),
    ]
