# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-21 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0006_remove_show_loop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(db_index=True),
        ),
    ]
