# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-25 12:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0007_auto_20160521_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 25, 12, 12, 53, 744300, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 25, 12, 13, 3, 859867, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
