# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-13 01:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0007_auto_20160309_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='show',
            name='settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='show', serialize=False, to='l8pr.ShowSettings'),
        ),
    ]
