# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-13 15:22
from __future__ import unicode_literals

import awesome_avatar.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=awesome_avatar.fields.AvatarField(default='nothing', upload_to='avatars'),
            preserve_default=False,
        ),
    ]
