# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-01 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0010_auto_20160601_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='show_type',
        ),
        migrations.AlterField(
            model_name='item',
            name='provider_name',
            field=models.CharField(blank=True, choices=[('YouTube', 'YouTube'), ('SoundCloud', 'SoundCloud'), ('Vimeo', 'Vimeo')], max_length=255, null=True),
        ),
    ]
