# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0011_auto_20160601_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='show', to='l8pr.ShowSettings'),
        ),
    ]
