# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-18 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0011_auto_20160313_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='show', to='l8pr.ShowSettings'),
        ),
    ]
