# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0012_auto_20160608_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='provider_name',
            field=models.CharField(blank=True, choices=[('YouTube', 'YouTube'), ('SoundCloud', 'SoundCloud'), ('WebTorrent', 'WebTorrent'), ('Vimeo', 'Vimeo')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.TextField(db_index=True, max_length=400),
        ),
    ]
