# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0013_auto_20160613_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsrelationship',
            options={'ordering': ('-order',)},
        ),
    ]
