# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 15:47
from __future__ import unicode_literals

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist


def add_to_group(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")
    try:
        api_user = Group.objects.get(name="api user")
        for user in User.objects.all():
            user.groups.add(api_user)
    except ObjectDoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0014_auto_20160624_1546'),
    ]

    operations = [
        migrations.RunPython(add_to_group),
    ]
