# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0015_auto_20160624_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showsrelationship',
            options={'ordering': ('-order', '-id')},
        ),
    ]
