# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0016_auto_20160625_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsettings',
            name='force_giphy',
            field=models.BooleanField(default=False),
        ),
    ]
