# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.core.exceptions import ObjectDoesNotExist


def migrate_settings(apps, schema_editor):
    Show = apps.get_model("l8pr", "Show")
    ShowSettings = apps.get_model("l8pr", "ShowSettings")
    ShowSettings.objects.exclude(id__in=[s['settings'] for s in Show.objects.all().values('settings')]).delete()
    for show in Show.objects.all():
        try:
            settings = ShowSettings.objects.get(id=show.settings.id)
            show.showsettings_set.set([settings])
            print('updated %s', show.title, settings.show.title, settings.id)
        except ObjectDoesNotExist:
            print('created %s', show.title)
            settings = ShowSettings.objects.create(show=show)


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0017_showsettings_force_giphy'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsettings',
            name='show',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='l8pr.Show'),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_settings),
        migrations.RemoveField(
            model_name='show',
            name='settings',
        ),
        migrations.AlterField(
            model_name='showsettings',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='l8pr.Show'),
        ),
    ]
