# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0018_auto_20160630_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsettings',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='l8pr.Show'),
        ),
    ]
