# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0019_auto_20160630_1038'),
    ]

    def complete_thumbnail(apps, schema_editor):
        Item = apps.get_model("l8pr", "Item")
        for item in Item.objects.all():
            if item.thumbnail.startswith('//'):
                item.thumbnail = 'https:%s' % (item.thumbnail)
                item.save()

    operations = [
        migrations.RunPython(complete_thumbnail),
    ]
