# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0026_auto_20170503_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shows',
            field=models.ManyToManyField(related_name='ItemsRelationship', through='l8pr.ItemsRelationship', to='l8pr.Show'),
        ),
    ]
