# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0027_item_shows'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsrelationship',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemsrelationship',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
