# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l8pr', '0028_auto_20170503_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followers', to='l8pr.Profile'),
        ),
    ]
